OpenDataNTNU/OpenData

frontend/.eslintrc.json, frontend/__tests__/App.test.jsx, frontend/__tests__/Redux/ActionCreators/Alert.test.jsx, frontend/__tests__/Redux/Reducers/Alert.test.jsx, frontend/package.json, frontend/src/App.jsx, frontend/src/index.jsx, frontend/src/router.jsx, frontend/src/sharedComponents/Alert.jsx, frontend/src/state/actions/alert.js, frontend/src/state/constants/alert.js, frontend/src/state/helpers/localstorage.js, frontend/src/state/reducers/alert.js, frontend/src/state/reducers/index.js, frontend/src/state/store.js, frontend/yarn.lock
=> Redux alerts ⚡️

frontend/__tests__/App.test.jsx, frontend/__tests__/Redux/ActionCreators/Alert.test.jsx, frontend/__tests__/Redux/Reducers/Alert.test.jsx, frontend/package.json, frontend/src/App.jsx, frontend/src/global-styles.jsx, frontend/src/index.jsx, frontend/src/pages/Splash/index.jsx, frontend/src/router.jsx, frontend/src/sharedComponents/Alert.jsx
Eslint wasnt scannig .jsx files because of missing config. Also fixed like 300 linting errors that it didnt catch from the first pull request.
=> Eslint fil scan config and linting errors fix

frontend/__tests__/App.test.jsx, frontend/__tests__/sharedComponents/Dropdown.test.jsx, frontend/__tests__/sharedComponents/Header.test.jsx, frontend/__tests__/sharedComponents/Template.test.jsx, frontend/src/App.jsx, frontend/src/global-styles.jsx, frontend/src/pages/Splash/index.jsx, frontend/src/sharedComponents/Alert.jsx, frontend/src/sharedComponents/Dropdown.jsx, frontend/src/sharedComponents/Footer.jsx, frontend/src/sharedComponents/Header.jsx, frontend/src/sharedComponents/Template.jsx
Thoughts? anything that seems off and how is the design? I followed elias' mockups, but added my own design on the dropdown menu as his mockup wasnt responsive.
=> Created page template with header and footer

frontend/src/sharedComponents/Header.jsx
Made the nav take up height of 100%
=> Fixed nav height in header

frontend/__tests__/ErrorBoundary.test.jsx, frontend/src/ErrorBoundary.jsx, frontend/src/index.jsx
Closes #24 
Feel free to change the design Elias, I am no designer.
=> Added error boundary to frontend app

backend/Controllers/MetadataController.cs, backend/Controllers/MetadataTypeController.cs, backend/Exceptions/HttpException.cs, backend/Middleware/HttpExceptionMiddleware.cs, backend/README.md, backend/Startup.cs, container/development/Dockerfile.nginx, container/development/docker-compose.yml, container/development/nginx.conf
* Properly proxy the frontend and backend together
* Proper error handling
=> Quality of Life improvements to the backend

Documentation/troubleshooting_the_backend.md, backend/Controllers/ExperiencePostController.cs, backend/Controllers/MetadataController.cs, backend/Domain/Models/ExperiencePost.cs, backend/Domain/Models/ExperiencePostTagMapping.cs, backend/Domain/Models/Metadata.cs, backend/Domain/Repositories/IExperiencePostRepository.cs, backend/Domain/Services/Communication/SaveExperiencePostResponse.cs, backend/Domain/Services/IExperiencePostService.cs, backend/Mapping/ModelToResourceProfile.cs, backend/Persistence/Contexts/AppDbContext.cs, backend/Persistence/Repositories/ExperiencePostRepository.cs, backend/Resources/ExperiencePostResource.cs, backend/Resources/ExperiencePostTagMappingResource.cs, backend/Resources/MetadataResource.cs, backend/Resources/SaveExperiencePostResource.cs, backend/Services/ExperiencePostService.cs, backend/Startup.cs
This PR contains API for creating experience posts for metadata. No user ownership yet, but it is coming.
=> Experience posts

backend/Resources/SaveExperiencePostResource.cs
This affects the creation of experience posts.
=> Add title to experience posts

backend/Startup.cs, backend/backend.csproj
Added the generation of XML documentation, and enabled such that swagger reads the xml documentation and displays it accordingly.
=> Swagger now displays descriptions and info about parameters

backend/Controllers/UserController.cs, backend/Persistence/Repositories/UserRepository.cs, backend/Startup.cs
Added the ability to get user information for REST calls, and an example in the rest call api/user/profile.
=> Added the ability to get user information for REST calls

backend/Controllers/UserController.cs, backend/Domain/Repositories/IUserRepository.cs, backend/Domain/Services/IUserService.cs, backend/Persistence/Repositories/UserRepository.cs, backend/Services/UserService.cs
Though I added this to #68. Simplifies fetching of a given user by mail.
=> Streamlined the fetching of a given user by mail

backend/Controllers/UserController.cs, backend/Domain/Models/User.cs, backend/Domain/Repositories/IMunicipalityRepository.cs, backend/Domain/Services/IMunicipalityService.cs, backend/Persistence/Contexts/AppDbContext.cs, backend/Persistence/Repositories/MunicipalityRepository.cs, backend/Resources/NewUserResource.cs, backend/Resources/PrivateSafeUserResource.cs, backend/Resources/SafeUserResource.cs, backend/Services/MunicipalityService.cs
Added a check when creating a user that connects the user to a municipality iff the user uses a main with the municipality mail domain.
=> Connects the user to a municipality if using municipality domain and usertype municipality

frontend/public/index.html, frontend/src/router/router.jsx, frontend/src/sharedComponents/SubHeader.jsx
router permissions
menu showing links depending on rank
File paths fix
=> Fixed minor errors

frontend/mockups/ErrorBoundary.html, frontend/mockups/Inspection.html, frontend/mockups/Login.html, frontend/mockups/MainView.html, frontend/mockups/Signup.html, frontend/mockups/SubmitData.html, frontend/mockups/mainMockup.css
=> Patch 2-02: Re-added mockups because they are missing in master.

backend/Controllers/MetadataController.cs, backend/Domain/Models/Like.cs, backend/Domain/Models/LikeReport.cs, backend/Domain/Models/Metadata.cs, backend/Domain/Repositories/ILikeRepository.cs, backend/Domain/Services/Communication/SaveLikeResponse.cs, backend/Domain/Services/ILikeService.cs, backend/Persistence/Contexts/AppDbContext.cs, backend/Persistence/Repositories/LikeRepository.cs, backend/Resources/LikeResource.cs, backend/Services/LikeService.cs, backend/Startup.cs
The ability to add likes is not in this PR, it will come at a later date.
=> Add database support for likes

backend/Controllers/MetadataController.cs, backend/Controllers/MetadataTypeController.cs, backend/Domain/Models/Comment.cs, backend/Domain/Models/Metadata.cs
This PR wishes to remove the warnings our github actions generates for the backend.
Closes #134
=> Remove some of the backend warnigns that pollute PR's

backend/Controllers/MetadataController.cs, backend/Persistence/Contexts/AppDbContext.cs, backend/Resources/SaveMetadataResource.cs, frontend/src/pages/SendMetadata/MetadataForm.jsx
It is now allowed to not provide an url on an unreleased dataset.
=> Story 15 - Fixed support for unreleased datasets

frontend/src/sharedComponents/Header.jsx, frontend/src/sharedComponents/HeaderLink.jsx
=> Header links highlight current location

frontend/src/sharedComponents/Header.jsx
Fixed the header responsiveness because it got fucked up from people adding new elements without updating the size constraints.
=> fixed header responsivness because of updated length

frontend/src/pages/About/index.jsx, frontend/src/router/router.jsx
Added a basic page with some info on /about
=> Add basic about page

backend/Persistence/Repositories/UserRepository.cs
If we wanna handle token timeouts by removing it, this PR handles it.
It removes expiry from new tokens.
Closes #132.
=> Removed token timeout

frontend/src/pages/EditDescriptionMetadataType/DescriptionEditBody.jsx, frontend/src/pages/EditDescriptionMetadataType/SingleDescription.jsx
Add some basic info about the voting system to the description voting page. If you feel that there is more information that should be added, or if it should look differenty, please come with suggestions - this was made in a hurry.
=> Added some explanatory text to description voting page

frontend/src/pages/MetadataByType/MetadataByTypeResults.jsx, frontend/src/pages/MetadataByType/index.jsx
=> Fixed metadata by type overflow bug
